- css/style.css
- index.html
#10 solved  : - feature = subscribe to newsletter added
> subscribe to newsletter feature added

- contact.html
- css/style.css
- index.html
- topics-detail.html
- topics-listing.html
Added login page to the website 
Fixes #3 
> This PR fixes the missing Login Page of the website.
> The Login Page contains animation applied to the top. 
> The login page gets popped on the screen making background fadeout .
https://github.com/user-attachments/assets/e22ad266-54cb-4e5d-befd-fee91857c715
> Added Login Page With Responsive UI

- contact.html
- css/style.css
- index.html
- topics-detail.html
- topics-listing.html
Added signup form for user registration for issue no #16 
If you are satisfied with it please add it to your project 
Thankyou!
> Added signup form 

- add-topics.html
- contact.html
- index.html
- topics-detail.html
- topics-listing.html
added page to fill topics detail.
solved issue #4
> Added page to add   topic details 

- index.html
- testimonial.css
Fixes: #29
This PR involves :-
i) Alignment of Testimonials images
ii) Adjusting Upper left quadrant width for proper text visibility
BEFORE
AFTER
> Fixes based on feedback (Testimonials Misaligned Images)

- Baselink.js
- add-topics.html
- index.html
- package-lock.json
- package.json
- server/controller/insight.controller.js
- server/package-lock.json
- server/package.json
- server/routes/insight.route.js
- server/utils/cloudinary.utils.js
- topics-detail.html
- topics-listing.html
- vercelbackup.txt
I have added backend for adding topic in the add-topics page. 
There is file name `Baselink.js` change the url to you backend base url .
> Adding the backend for `add-topics.html` page

- contact.html
- index.html
- js/login.js
- js/signup.js
- server/api/app.js
- server/api/dbconnect.js
- server/api/index.js
- server/controller/authController.js
- server/models/User.js
- server/package-lock.json
- server/package.json
- server/routes/authRoutes.js
- topics-detail.html
- topics-listing.html
Pull Request Description #15 :
Overview: This PR introduces a backend implementation for the login and sign-up functionality of the application. It connects the front-end forms for signing up and logging in with the backend, allowing users to create accounts, authenticate, and receive tokens for subsequent requests.
Key Changes:
Backend Routes:
Implemented POST routes for /api/auth/signup and /api/auth/login to handle user registration and login, respectively.
Added server-side validation for username, email, and password.
On successful signup, the server returns a JWT token for authenticated requests.
Frontend Integration:
The login form now sends a POST request to the /api/auth/login endpoint with email and password.
On successful login, the user is redirected to the home page and a …
> Added Backend to login and signup pages

- add-topics.html
- contact.html
- css/style.css
- index.html
- topics-detail.html
- topics-listing.html
fixed: #26
Description
--
1. Moved the copyright text to the very bottom of the webpage.
2. Adjusted the width to span the full page, maintaining responsiveness across all screen sizes.
3. Styled the tag to align with the existing color palette for a consistent look and feel.
4. Ensured the implementation does not affect the overall code flow or layout structure of the webpage.
5. Verified that the design is responsive and adapts seamlessly to various devices and resolutions.
Screenshots
--
Before:
After:
Testing Steps
--
1. Open the webpage on different devices and screen resolutions to check the responsiveness.
2. Verify that the footer remains aligned and styled according to the color palette.
3. Confirm no unintended layout changes occur on other components.
notify me for further …
> updated copyright containing tag and bought it to the very bottom

- add-topics.html
fixed: #55
Added placeholder in add-topics.html in input and textarea fields.
preview
> added placeholder in add-topics.html

- css/style.css
fixes:#60
Increased the width of drop-down menu under Pages section for mobile view
> Increase width of menu

- index.html
> content on the index.html is ready #1

- add-topics.html
Added a responsive footer with all footer links: #65
> Added Responsive footer to add-topics.html 

- contact.html
Issue #78 
Added Testimonials and Browse topics in footer and linked them with respective pages
> Add Testimonials & Browse Topics in Footer of CONTACT PAGE

- add-topics.html
- contact.html
Added testimonials and browse topics to add-topics.html page and connected them with there respective pages
Issue #81 
Also, kindly assign pts under SWOC
Thanks and regards !
> Added testimonials and browse topics to add-topics.html page

- README.md
> Added a dynamically updating contributors list in README.md

- add-topics.html
Fixes #76 
**Files Modified** : add-topics.html
**Changes I made** :
- A non-closable modal prompt in "add-topics.html" until the user logs in
- The login & signup modal won't also close until the user logs in
Demo Video :
https://www.loom.com/share/173da2f7c32c435199d5404b093fd87b?sid=daea31b6-e7c1-4fc9-9ef8-b60d5357186a
> "login prompt for non-logged in users added in add-topics page"

- index.html
> accordian is now fixed, closed by default

- css/style.css
- index.html
**Description:**  
This PR proposes the addition of an **AI chatbot** to the website to assist new users in exploring and understanding its features. The chatbot will provide context-based guidance, answer common questions, and make navigation more intuitive, ensuring an improved user experience.  
**Issue Fixed** #14 
**Key Features:**  
1. **User Guidance:**  
- The chatbot will guide users through the website, explaining key features and functionalities.  
2. **FAQ Support:**  
- Provides instant answers to frequently asked questions to streamline user interactions.  
3. **Context-Based Assistance:**  
- Offers tailored support based on user actions and preferences, improving usability.  
4. **Seamless Integration:**  
- Matches the website’s design aesthetics and integrates smoothly …
> Integrate AI Chatbot for Enhanced User Guidance and Support

- contact.html
- profile.html
Bug fix of: #64 & #23
from PR: #85
https://drive.google.com/file/d/1rXvgZpv6AhkTAiIbi6LDa3q_z6uNwPLG/view?usp=sharing
> Bug in contactPage  and profile pages (and topics listing page style)

- topics-detail.html
fixes: #95 
Added links in the navbar of topics-detail.html page @Dishika18
> Added Links of different sections of Home Page in topics-detail.html in Navbar

- topics-listing.html
fixes: #96 
Added links of home page in navbar of topics-listing.html @Dishika18
> Add Links of different sections of Home Page in topics-listing.html of NAVBAR

- add-topics.html
Fixes #111 
**Files modified** : add-topics.html
**Changes I made** :
- Removed unneccessary form actions from 'login' & 'signup' form
- Added 'loginForm' id
- Added 'js/login.js' & 'js/signup.js' js files
**Demo Video**:
https://www.loom.com/share/934e5e8b4b554d9db825cba947e09fe1?sid=c65d96a8-81a5-48c8-bd3d-c86fdee69950
> Fixed login & signup in add-topics page

- profile.html
fixes: #133 
Added links of home page in navbar of profile.html
> Added links of home page in profile.html

- server/controller/profile.controller.js
- server/models/User.js
- server/routes/profile.routes.js
I have added this profile controllers for the application:
Fixing #131 
Routes:
- `/editprofile` this take fields to edit as form-data body ( "image" is the filed )
- `/deleteprofile` route for deleting profile,
-  `/getinsights` route for getting all the insights of the particular user
getprofile
editprofile
getinsights
> Added more  profile controllers

- css/style.css
Fix #138
Files modified : add-topics.html
Changed the submit button color in add-topics.html to match the submit button color in contact.html.
style.css
```
.btn-primary {
background-color: var(--custom-btn-bg-color);
border: none;
border-radius: 5px;
padding: 0.5rem 1.5rem;
font-weight: bold;
color: var(--white-color);
font-family: var(--title-font-family);
}
.btn-primary:hover {
background-color: var(--custom-btn-bg-hover-color);
}
```
Screenshot
> fix: fix submit color in add-topic.html

- server/models/User.js
- server/models/insight.model.js
- topics-listing.html
Fixing #137 
I have added search and sort function in the topics listing page. the sort function works on time like oldest or newest topic
Video:
https://github.com/user-attachments/assets/3db0e27a-78ec-4c94-b7d3-5c6148873061
> added search and sort function

- contact.html
- js/contacts.js
- server/api/.env.sample
- server/api/app.js
- server/api/dbconnect.js
- server/api/index.js
- server/models/contact.js
- server/routes/contact.route.js
fixes: https://github.com/Dishika18/InsightSync/issues/127
new files added 
1)contacts.js ->js folder 
2)contact.routes.js -> routes folder 
3)contact.js -> model folder
added code to dbconnect.js,index.js,
> adding files for database connection for contact file

- edit-profile.html
- profile.html
- server/controller/insight.controller.js
- server/routes/insight.route.js
I have added edit profile section 
Fixing #143 
Video
https://github.com/user-attachments/assets/9844a7e1-5627-4255-9605-d4a5539d837f
> Added edit profile section

- add-topics.html
- contact.html
- feedbackform.css
- feedbackform.html
- feedbackform.js
- index.html
- topics-detail.html
- topics-listing.html
Fixes:#118
I have added link on footer
@Dishika18 Please review
> Add feedback form

- index.html
Issue no #129 
This animation created a dynamic visual effect but:
Was not immediately readable.
Could distract users.
Depended on an external resource.
The tag was replaced with static, center-aligned text.
This ensures:
The text is instantly visible and readable.
The website avoids reliance on external services, improving performance and reliability.
> Change Login & Signup Text to Static and removed the Emoji

- css/style.css
- topics-listing.html
Fixes : redesign search bar (#145)
- redesigned the search bar in Topics Listing Page.
- made it according to the color theme of website
- it is similar to the search bar in home page
> redesigned search box

- edit-insight.html
- topics-detail.html
Here is a working video:
issue number #149 
https://github.com/user-attachments/assets/9cec5c6a-348e-42df-bb6f-e5022c0ac81c
I have also changed the edit button which is not shown in the video
> added edit insight frontend page

- add-topics.html
- contact.html
- css/style.css
- edit-profile.html
- index.html
- js/contacts.js
- js/login.js
- js/signup.js
- profile.html
#157 
I have styled the notification on all the pages according to there status (error and success)
can you please make it advance instead of intermediate because I changed it for each and every notification and also set the redirection after it so...
> #157-notifications styled

- index.html
**fixed issue no: #161**
---
**Description:**
I’ve just updated the login page by adding **placeholder text** in the email and password input fields! 🎉 The placeholder helps users by showing example text or hints about the expected input, improving the overall user experience. ✨
✅ **Email field**: Added placeholder “Enter your email” 📧  
✅ **Password field**: Added placeholder “Enter your password” 🔒
This simple update makes the page more intuitive, guiding users to fill out the form easily. 🌟 Stay tuned for more UI/UX enhancements coming soon! 💻
---
**Preview**
---
---
> 🚀 Enhanced Login Page with Placeholder Text 📝

- add-topics.html
- contact.html
- feedbackform.html
- index.html
- topics-detail.html
- topics-listing.html
**issue no: #161**
**previous pr #162**
---
🛠️ **What's New?**  
I have enhanced the user experience by adding meaningful placeholders to input fields across various pages. Here's a detailed breakdown of the changes:  
1️⃣ **Login Page**:  
- Added a placeholder to the **email field** for clarity, e.g., `Enter your email address`.  
- Added a placeholder to the **password field**, e.g., `Enter your password`.  
2️⃣ **Signup Page**:  
- Included placeholders for **username**, **email**, and **password** fields for better form guidance.  
3️⃣ **Contact Page**:  
- Enhanced placeholders in the **name**, **email**, and **message fields** to prompt users about the required input.  
4️⃣ **Feedback Form**:  
- Clear instructions through placeholders for **name**, **email**, **rating**, and …
> 🚀 Added Placeholders to Multiple Pages for Better UX! 🎨

- add-topics.html
- contact.html
- feedbackform.html
- index.html
- topics-detail.html
- topics-listing.html
fixes: #168 
Added dynamic year change feature on all pages
@Dishika18
> Added dynamic year change feature on all pages

- IndexPage.js
- add-topics.html
- index.html
- js/login.js
- server/api/app.js
- server/controller/insight.controller.js
Fixes #159 
Video: 
without topics
https://github.com/user-attachments/assets/53e34f13-894f-4cd5-9275-8baf0dbe06d8
with topics
https://github.com/user-attachments/assets/29727768-0844-4aec-8aa1-1bd81657e5bb
When the insights are below 2-3 there will be no content diplayed. I added this check to maintain 3 cards always. I also keep the styles as before
> Added topics from db in index page

- js/signup.js
- server/controller/insight.controller.js
- topics-listing.html
I have added sorting by topics
Fixing #176 
Video:
https://github.com/user-attachments/assets/bf338b98-2306-4269-9d58-f23c7cdc267e
> Added sorting by topics

- add-topics.html
- contact.html
- css/style.css
- feedbackform.html
- index.html
- topics-detail.html
- topics-listing.html
fixes #31
- Fixed the Login SignUP buttons
- They redirect to correct pages
- Dropdown arrow is now in right as it should be
- Fixes #31
> Fixed Login/Signup Buttons in Mobile View

- IndexPage.js
- index.html
Added random topics in the index page make it look more dynamic
Video:
https://github.com/user-attachments/assets/7e3a8e23-d73f-4904-b3a6-3b9f9d83848e
> add random topics on index page

- server/controller/insight.controller.js
- server/models/User.js
- server/models/insight.model.js
- server/routes/insight.route.js
I have added like functionality
Fixes #179 
how to test:
- login using postman the login route is `http://localhost:3000/api/v1/auth/login`, the output will be like below image:
- get the token and send a post req to the endpoint url `http://localhost:3000/api/v1/insight/like/insight_id`, on successfull the response will be like this 
and if the article is already like it will be removed from liked array
- then check the status of the articles with the `getallinsight` endpoint
> added like functionaly backend

- contact.html
Fixes #174 
https://insight-sync-li1dp651w-thunderblazes-projects.vercel.app/contact.html
> Fixed the issue of not being able to Login & Signup from Contact Page

- testimonial.css
- Fixed Testimonial Images
- Fixes #187
> Fixed Testimonial Images

- js/login.js
- server/controller/authController.js
- topics-detail.html
fixing #180 
I have added like functionality frontend
Video:
https://github.com/user-attachments/assets/b7d19edd-c81b-4113-be7d-60981669cf9f
> added liked functionality

- add-topics.html
fixing #193 
i have added markdown support , user can  now also add markdown text 
SS:
> added markdown support

- topics-listing.html
fixes: #194 
Added links of particular sections of home page in the Navbar of topics-listing.html @Dishika18
> Added Links in navbar of topic listing page

- feedbackform.html
fixes: #195 
Added links of different sections of home page in feedbackform @Dishika18
> Add links to the feedback form

- profile.html
- topics-detail.html
I have added save for later frontned part. Users can now save any article from the fronend and view the saved topics from frontned
Video:
https://github.com/user-attachments/assets/98e9f8ac-312f-4de6-bc7a-b5bdc86fbb92
> added savefor later fronend

- add-topics.html
- contact.html
- feedbackform.html
- index.html
- profile.html
- topics-detail.html
- topics-listing.html
I have added logout feature for the pages
Fixing #75
> added Logout feature

- topics-detail.html
fixes: #206 
Added links of particular sections of home page in the navbar of topics-detail.html
@Dishika18
> Added links in navbar of topics-detail.html

- css/style.css
- index.html
in this pr i have improve some decent Ish  in ui of footer .
> footer ui improve

- server/controller/insight.controller.js
- server/controller/profile.controller.js
- server/routes/profile.routes.js
- topics-detail.html
#213
I have added a public profile controller which will be used to fetch public profile
The route is 
http://localhost:3000/api/v1/profile/getpublicprofile?username=<the_username_to_search>
I have also add the details , who published the article this can be used to fetch public profile
> i have added the public profile controllers

- add-topics.html
- contact.html
- css/Scroll.css
- feedbackform.html
- index.html
- js/click-scroll.js
- topics-listing.html
Related Issue
Fixes - #222
Description
This PR introduces an animated scroll-to-top button that will be available on all pages of the website. The button becomes visible when the user scrolls down and smoothly scrolls the page back to the top when clicked. This feature enhances user navigation and overall experience.
> Add Animated Scroll-to-Top Button Across All Pages.

- server/api/app.js
- server/controller/comment.controller.js
- server/models/User.js
- server/models/comment.model.js
- server/models/insight.model.js
- server/routes/comment.router.js
#220
I have implemented comment section functinality
This routes and controllers can be used for the comment section management. This are all protected routes so authorization header is required.
SS:
add a comment , route - `http://127.0.0.1:3000/api/v1/comment/addcomment`
requestbody:
```
{
"i_id":"67b753a409d5b18b0551d619",
"comment":"test comment 3"
}
```
get all comments, route:`http://127.0.0.1:3000/api/v1/comment/getcomments`
> Implement comment functionality with add, get, and delete operations

- addcomment.js
- fetchcomment.js
- server/controller/comment.controller.js
- server/routes/comment.router.js
- topics-detail.html
I have added the frontend part for the comments functionality
Issue #221 
Video:
https://github.com/user-attachments/assets/f3b0146d-703b-4355-83a6-98748bea72cb
> Add functionality to fetch comments by insight ID and update comment handling

- index.html
#224
fixed the issue on the home page
> fixed the copyright on the home page

- topics-listing.html
- Added Sort by Liked feature in the Topic Listing page
- Fixes #208
> Added Sorting by Likes

- puplicprofile.html
- server/controller/profile.controller.js
- server/routes/profile.routes.js
- topics-detail.html
#214
I have added a public profile page in the website. For now it is basic with time many functionality can be addedlater
> Update public profile route and link in topics detail page

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
closes #234 
Added PR and issue template
> Added pr and issue template

- .vscode/settings.json
- contact.html
Title : Navbar not working in contact form page
Closes #233 
the navbar links made working in contact form
apertre2.0
> made navbar working in contact section

- IndexPage.js
- index.html
This pull request introduces a feature to enable users to search for topics and display search results dynamically on the `IndexPage.js` and `index.html` files. The most important changes include adding a debounce function for efficient search input handling, implementing asynchronous fetching of search results, and updating the HTML structure to support these functionalities.
* [`IndexPage.js`](diffhunk://#diff-a97ff99426278ddd2bfb314cc6168fb8edc88c2e178e6f1e6f0288ffaec6786bR7-R68): 
* Added a debounce function to handle search input efficiently and prevent excessive API calls.
* Implemented the `fetchResults` function to asynchronously fetch search results from the API and display them dynamically.
* Added event listeners to trigger the search functionality on input change and button …
> [FEATURE]: Implement Search Functionality for Topics

- profile.html
#211 
1.Make the changes of profile page suitable for different screens with changes in file profile.html of html and css.
2.made the profile-pic covers it parent.
**Additional context(if any)**
apertre2.0
> UI redesign for profile.html #211

- summary.js
- topics-detail.html
Close  issue #253 
AI-Powered Content Summarization – Use Gemini API to generate short summaries of lengthy articles.
> Added AI summarization feature

- 404.html
- add-topics.html
- contact.html
- edit-insight.html
- edit-profile.html
- feedbackform.html
- profile.html
- puplicprofile.html
- topics-detail.html
- topics-listing.html
Added favicons to all pages to improve branding and user experience. This ensures a consistent icon is displayed in browser tabs, bookmarks, and when saving the site as a shortcut.
**Additional context(if any)**
Yes, participating in Apertre 2.0
> Favicon added in all the pages

- 404.html
- add-topics.html
- index.html
- profile.html
- topics-detail.html
- topics-listing.html
Optimized SEO by adding essential meta tags to improve search engine visibility, social media sharing, and overall performance.
✅ Added viewport meta tag to ensure mobile responsiveness.
✅ Included meta description to enhance search engine rankings.
✅ Added relevant keywords to improve discoverability.
✅ Specified author meta tag for better attribution.
✅ Set robots meta tag to allow search engines to index and follow links.
✅ Implemented Open Graph (OG) tags for better social media link previews.
✅ Added Twitter Card meta tag to improve link sharing on Twitter.
- Verified SEO improvements using Google Lighthouse and other audit tools.
- Ensured better mobile compatibility with the updated viewport settings.
- Improved social media sharing experience with OG and Twitter meta tags.
Yes, …
> Optimized SEO of the website by adding necessary meta tags
